on:
  pull_request:
  push:
    branches: main
name: Test
jobs:
  UnityTest:
    name: Test in playmode
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.4
    - name: Cache
      uses: actions/cache@v4.0.2
      with:
        path: ./Library
        key: Library-UnityTest
        restore-keys: Library-
    - name: Run playmode Tests
      uses: game-ci/unity-test-runner@v4.1.1
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        testMode: playmode
        artifactsPath: playmode-artifacts
        checkName: playmode test results
        coverageOptions: generateReport
    - name: Upload a Test Artifact
      uses: actions/upload-artifact@v4.3.3
      if: always()
      with:
        name: Test results for playmode
        path: playmode-artifacts
